ua-eas/ksd-kc5.2.1-ua

src/main/resources/org/kuali/kra/datadictionary/ProposalDevelopmentDocument.xml

The root issue here again lies with the (lack of) workflow header xml. 
The new rice generates around ten times less header xml. To change this, one needs to explicitly change DataDictionary entries to be additive. 
More specifically, I'm changing: 
src/main/resources/org/kuali/kra/datadictionary/ProposalDevelopmentDocument.xml 
from: 
{snip} 
<bean parent="WorkflowProperty" p:path="developmentProposalList.proposalPersonUnits"/> 
{/snip} 
to: 
{snip} 
<bean parent="WorkflowProperty" p:path="developmentProposalList.proposalPersons"/> 
<bean parent="WorkflowProperty" p:path="developmentProposalList.proposalPersons.units"/> 
{/snip} 
This small changed seems to corrected the issue of unit hierarchy nodes disappearing from a copied proposal.

UAR-899 - College of lead unit not appearing in workflow from copied proposal

---

src/main/webapp/css/uar_kuali_application.css

Added CSS to hide the send notification button for the ProposalDevelopment, IP, Award and Protocol modules.

UAR-960 Hide 'send notification' button on all modules

---

src/main/resources/ApplicationResources.properties

Changed property to correct value in ApplicationResources.properties.

UAR-969 Workflow annotation still says 'DOCUMENT REJECTED instead of 'DOCUMENT RETURNED FOR EDIT'

---

src/main/resources/edu/arizona/kc/db/changelog/changesets/db.changelog-UAR-1048.xml
src/main/resources/edu/arizona/kc/db/changelog/db.changelog-master.xml
src/main/resources/org/kuali/kra/datadictionary/NegotiationUnassociatedDetail.xml

UAR-993 Negotiation Log migration is dependent on this fix.
Tech Note: updated the Negotiation Unassociated Detail  maintenance document to allow maxLength on the title field to be 200 chars and added liquibase script to increase this field accordingly in the negotiation_unassoc_detail table.

UAR-1048, UAR-993: Increase the negotiation_unassoc_detail.title to allow 200 characters

---

src/main/resources/edu/arizona/kc/db/changelog/changesets/db.changelog-UAR-1023.xml
src/main/resources/edu/arizona/kc/db/changelog/db.changelog-master.xml
src/main/resources/org/kuali/kra/datadictionary/NegotiationActivity.xml

UAR-993: Negotiation Log migration depends on this fix.
Tech Note: updated the Description field maxLength to 4000 in the negotiationActivity maintenance document and added liquibase script to increase the negotiation_activity.description column to 4000 chars.

UAR-1023, UAR-993: Increase negotiation activity description to allow 4000 characters

---

src/main/java/org/kuali/kra/common/customattributes/CustomDataHelperBase.java
src/main/java/org/kuali/kra/proposaldevelopment/web/struts/action/ProposalDevelopmentAction.java
src/main/java/org/kuali/kra/rules/CustomDataRule.java
src/main/java/org/kuali/kra/web/struts/action/AuditMapSorter.java
src/main/webapp/WEB-INF/tags/summary/proposalDevelopmentCustomDataInformation.tag

Refactored propsalDevelopmentCustomDataInformation.tag, added keys for comparator regex, added logic so that custom data validation errors get sorted by name, not label, yet still displays the label in the UI, updated and renamed the comparator to compare by names rather than labels for the custom data fields, added code to populate the custom data information panel on the summary tab when a document is loaded.

UAR-1122 adjust custom data sort to use custom_attribute.name instead of custom_attribute.label

---

src/main/java/edu/arizona/kra/global/unit/create/UnitAdministratorCreateGlobalRule.java
src/main/java/edu/arizona/kra/global/unit/delete/UnitAdministratorDeleteGlobal.java
src/main/java/edu/arizona/kra/global/unit/delete/UnitAdministratorDeleteGlobalRule.java
src/main/java/org/kuali/kra/infrastructure/KeyConstants.java
src/main/resources/ApplicationResources.properties
src/main/resources/edu/arizona/kra/datadictionary/UnitAdminTypeAndPersonGlobalDetail.xml
src/main/resources/edu/arizona/kra/datadictionary/docs/UnitAdministratorCreateGlobalMaintenanceDocument.xml
src/main/resources/edu/arizona/kra/datadictionary/docs/UnitAdministratorDeleteGlobalMaintenanceDocument.xml
src/main/resources/repository.xml

* Added "template" attributes to the maintenance xml in order to get values to persist between screen states 
* Implemented Rule classes that enable validation and are responsible for display of any generated error messages 
* Rule classes to produce validation errors for dupe/missing UnitAdmin
*src/main/java/edu/arizona/kra/global/unit/create/UnitAdministratorCreateGlobalRule.java
*src/main/java/edu/arizona/kra/global/unit/delete/UnitAdministratorDeleteGlobalRule.java
* Change scope of method from public to protected, needed by rules
* src/main/java/edu/arizona/kra/global/unit/delete/UnitAdministratorDeleteGlobal.java
* Add two error entries, used by rule classes
* src/main/java/org/kuali/kra/infrastructure/KeyConstants.java
* src/main/resources/ApplicationResources.properties
* Changed …

UAR-973_2 - Allow bulk add and delete for unit administrator unit number

---

src/main/java/org/kuali/kra/web/struts/action/AuditMapSorter.java

Changing regex from:
"CustomDataInternalUseOnlyErrors|CustomDataProjectInformationErrors"
to:
"CustomData.*"

UAR-1122_2 - Widening the regex to catch all CustomData AudiClusters.

---

src/main/java/org/kuali/kra/timeandmoney/web/struts/action/TimeAndMoneyAction.java

I integrated the foundation fix into our KC version, and the issue appears to be resolved.
The actual code change was to take into account pending actions (or rather, lack of) when deciding to create a Single Node Transaction. If there are no pending actions, then the node is not created.

Awd T&M: Single Node Transaction zeroes out Award on subsequent save in T&M when in 'current' view

---

src/main/java/edu/arizona/kra/global/unit/create/UnitAdminCreateGlobalMaintainableImpl.java
src/main/java/edu/arizona/kra/global/unit/create/UnitAdminTypeAndPersonGlobalDetail.java
src/main/java/edu/arizona/kra/global/unit/delete/UnitAdminDeleteGlobalMaintainableImpl.java
src/main/java/edu/arizona/kra/global/unit/delete/UnitAdministratorGlobalDetail.java

Added a refresh method to UnitAdminCreateGlobalMaintainableImpl.java and UnitAdminDeleteGlobalMaintainableImpl.java set the personId and to add it into the field upon returning the value from the person lookup.  Adjusted the getPerson method in UnitAdminTypeAndPersonGlobalDetail.java and UnitAdministratorGlobalDetail.java to check if personId is not null and if so, check to make sure person was not null and compare the person.personId to personId and if they are the same, just return person, otherwise do a new getKcPersonByPersonId lookup to return the new person information.
Changed getPerson() conditions in the IF statement for UnitAdminTypeAndPersonGlobalDetail.java and UnitAdministratorGlobalDetail.java.  Removed two unnecessary lines from the refresh() method in …

UAR-1167 KC Person lookup with return value returns null on Unit Admin Create Global and Unit Admin Delete Global

---

src/main/java/edu/arizona/kra/irb/actions/print/CustomProtocolXmlStream.java

Fix CustomProtocolXmlStream.getQuestionnaireAnswerHeader to return an empty answer header instead of null.

UAR-263: Avoiding null pointer exceptions for QuestionnaireHeader

---

src/main/webapp/WEB-INF/tags/subaward/subAwardFundingSource.tag

Displaying pending subaward funding sources while they're being added and not display the row numbers - we still want the column present

UAR-1497: Upating the .tag file to display pending and remove indexes

---

src/main/java/org/kuali/kra/award/web/struts/action/AwardAction.java
src/main/java/org/kuali/kra/lookup/keyvalue/SubAwardFundingSourceValuesFinder.java
src/main/java/org/kuali/kra/medusa/service/MedusaServiceImpl.java
src/main/java/org/kuali/kra/service/VersionHistoryService.java
src/main/java/org/kuali/kra/service/impl/VersionHistoryServiceImpl.java
src/main/java/org/kuali/kra/subaward/SubAwardForm.java
src/main/java/org/kuali/kra/subaward/bo/SubAward.java
src/main/java/org/kuali/kra/subaward/bo/SubAwardFundingSource.java
src/main/java/org/kuali/kra/subaward/dao/SubAwardFundingSourceDao.java
src/main/java/org/kuali/kra/subaward/dao/impl/SubAwardFundingSourceDaoOjb.java
src/main/java/org/kuali/kra/subaward/service/SubAwardService.java
src/main/java/org/kuali/kra/subaward/service/impl/SubAwardServiceImpl.java
src/main/java/org/kuali/kra/subaward/subawardrule/SubAwardDocumentRule.java
src/main/java/org/kuali/kra/subaward/web/SubAwardFundingSourceBean.java
src/main/java/org/kuali/kra/subaward/web/struts/action/SubAwardAction.java
src/main/java/org/kuali/kra/subaward/web/struts/action/SubAwardHomeAction.java
src/main/resources/edu/arizona/kc/db/changelog/changesets/db.changelog-UAR-1497.xml
src/main/resources/edu/arizona/kc/db/changelog/db.changelog-master.xml
src/main/resources/org/kuali/kra/datadictionary/SubAwardFundingSource.xml
src/main/resources/org/kuali/kra/subaward/SubAwardSpringBeans.xml
src/main/resources/org/kuali/kra/subaward/repository-subAward.xml
src/main/webapp/WEB-INF/tags/subaward/subAwardFundingSource.tag

This fix considers that an Award and a Subaward are 'linked' if there is at least one ACTIVE SubAwardFundingSource object in the DB that references the corresponding AwardNumber and Subaward Code (note that there could be multiple SFS for the same Award/Subaward pair for the different versions of them). 
The business requirements state that ONLY one Award/Subaward link will be displayed, even if there are multiple SFS for the different versions and ONLY the ACTIVE/PENDING version should be displayed.
When a link is 'deleted', all the rows corresponding to the SFS are not removed any more, but marked as INACTIVE. As such, the removed 'link' will not be visible any more for ANY of the versions of the Awad/Subaward.
Added SubAwardFundingSourceDAO with custom PS, to improve the performance of …

UAR-1497 Fix for Versioning issues around Award and linked SubAwards through SubAwardFundingSources.

---

src/main/resources/org/kuali/kra/datadictionary/SubAwardAmountInfo.xml
src/main/resources/org/kuali/kra/datadictionary/SubAwardAmountReleased.xml

Changed validation rules for amounts in subaward to be consistent with 12 digits. Columns in the database already are set to this size.

UAR-1619 Allow numbers with 12 digits total for subaward amounts

---

src/main/java/org/kuali/kra/subaward/dao/impl/SubAwardFundingSourceDaoOjb.java

The issue that was fixed is that in case of Medusa, we are not in a transactional context so there is no default Persistence Broker to be used in the SubAwardFundingSourceDAO. The fix allows to create a new instance of a PB if one doesn't exist.

UAR-1641: Fix Medusa refresh issues in Subaward and Award

---

src/main/java/edu/arizona/kra/proposaldevelopment/PropDevRoutingStateConstants.java
src/main/java/edu/arizona/kra/proposaldevelopment/bo/SPSRestrictedNote.java
src/main/java/edu/arizona/kra/proposaldevelopment/dao/SPSRestrictedNoteDao.java
src/main/java/edu/arizona/kra/proposaldevelopment/dao/ojb/PropDevRoutingStateDaoOjb.java
src/main/java/edu/arizona/kra/proposaldevelopment/dao/ojb/SPSRestrictedNoteDaoOjb.java
src/main/java/edu/arizona/kra/proposaldevelopment/service/PropDevRoutingStateService.java
src/main/java/edu/arizona/kra/proposaldevelopment/service/impl/PropDevRoutingStateServiceImpl.java
src/main/java/org/kuali/kra/infrastructure/KeyConstants.java
src/main/java/org/kuali/kra/proposaldevelopment/bo/DevelopmentProposal.java
src/main/java/org/kuali/kra/proposaldevelopment/web/struts/action/ProposalDevelopmentAbstractsAttachmentsAction.java
src/main/java/org/kuali/kra/proposaldevelopment/web/struts/form/ProposalDevelopmentForm.java
src/main/resources/ApplicationResources.properties
src/main/resources/edu/arizona/kc/db/changelog/changesets/db.changelog-UAR-1609.xml
src/main/resources/edu/arizona/kc/db/changelog/db.changelog-master.xml
src/main/resources/edu/arizona/kra/datadictionary/SPSRestrictedNote.xml
src/main/resources/edu/arizona/kra/proposaldevelopment/CustomPropDevSpringBeans.xml
src/main/resources/org/kuali/kra/proposaldevelopment/ProposalDevelopmentSpringBeans.xml
src/main/resources/repository.xml
src/main/webapp/WEB-INF/jsp/proposaldevelopment/ProposalDevelopmentAbstractsAttachments.jsp
src/main/webapp/WEB-INF/tags/proposaldevelopment/proposalSPSNotes.tag

Added new SPSRestrictedNote business object with appropriate DataDictionary file, DaoOjb and methods in the PropDevRoutingStateService to be able to add,search and delete an SPS Restricted Note. The new table is linked in repository.xml. Added new tag file proposalSPSNotes.tag displayed in ProposalDevelopmentAbstractsAttachments.jsp just below the 'normal' notes
Also made modifications in PropDevRoutingStateDaoOjb to retrieve the Yes/No for the Final Proposal Received column.
The SPS Restricted Notes, same as the other 'normal' notes on a Proposal are EDITABLE even when the proposal is not in an editable state. The consequence is that notes can be added/deleted from the proposal without having to save it/edit it by the users who have corresponding rights (in this case Edit SPS Restricted …

UAR 1609 - Add SPS Restricted Notes Functionality to Proposal Development

---

src/main/java/org/kuali/kra/irb/ProtocolAction.java
src/main/java/org/kuali/kra/irb/actions/ProtocolProtocolActionsAction.java
src/main/java/org/kuali/kra/irb/noteattachment/ProtocolNoteAndAttachmentAction.java
src/main/resources/edu/arizona/kc/db/changelog/changesets/db.changelog-UAR-1489.xml
src/main/resources/edu/arizona/kc/db/changelog/db.changelog-master.xml

Moved the implementation for getProtocolAttachmentFile in the super action: ProtocolAction and changed the implementation to allow watermarks for docStatus='2' and protocolStatus 400 and 401 where the attachment is complete. Removed redundant checks related to protocol attachment versions.
Also added liquibase script to change the appropriate rows in the watermark table.

UAR-1489:Changing implementation in ProtocolAction for getProtocolAttachmentFile() to include protocol statuses 400 and 401

---

src/main/java/org/kuali/kra/subaward/service/impl/SubAwardServiceImpl.java

Adding comparator to sort subaward amount infos on the id, which would reflect the historic order in which they were created.

UAR-1785:History of Changes panel in Subaward not displaying in correct order

---

src/main/java/edu/arizona/kra/proposaldevelopment/PropDevRoutingStateConstants.java
src/main/java/edu/arizona/kra/proposaldevelopment/bo/ProposalDevelopmentRoutingState.java
src/main/java/edu/arizona/kra/proposaldevelopment/dao/ojb/PropDevRoutingStateDaoOjb.java
src/main/java/edu/arizona/kra/util/DBConnection.java
src/main/resources/edu/arizona/kra/datadictionary/ProposalDevelopmentRoutingState.xml

Added workflow unit to the DD and BO then added workflow unit query to dao.
The logic is to find first the units associated with the workflow unit that the user mentions, from there identify the related proposal numbers and use them filter the current results from the dashboard (only when the user specifies a workflow unit)
Technical Debt: Refactored ProposalRoutingDaoOjb to use DBConnection to make sure connection resources are allocated/released properly.

UAR-1708: Adding additional query for workFlow unit to the Proposal Routing Dashboard

---

src/main/java/org/kuali/kra/award/lookup/AwardLookupableHelperServiceImpl.java
src/main/java/org/kuali/kra/institutionalproposal/service/impl/InstitutionalProposalLookupableHelperServiceImpl.java

Remove filtering of results returned on lookups based on user permissions.
Result row will contain open, copy, medusa actions when the user has the permissions to open the Award/IP document.

UAR-2189: Fixing filtering Issues in Award and IP lookups

---

src/main/java/org/kuali/kra/subaward/web/struts/action/SubAwardAction.java
src/main/resources/org/kuali/kra/subaward/repository-subAward.xml

Removed duplicate columns from subaward reporsitory file and improve SubAwardAction to query for SubAward Funding Sources only when the SubAward is not new.

UAR-1685: Fixing stack trace at subaward lookup

---

src/main/java/org/kuali/kra/proposaldevelopment/questionnaire/ProposalDevelopmentQuestionnaireHelper.java
src/main/java/org/kuali/kra/proposaldevelopment/web/struts/action/ProposalDevelopmentKeyPersonnelAction.java
src/main/java/org/kuali/kra/proposaldevelopment/web/struts/form/ProposalDevelopmentForm.java
src/main/webapp/WEB-INF/jsp/proposaldevelopment/ProposalDevelopmentKeyPersonnel.jsp
src/main/webapp/WEB-INF/tags/questionnaire/revenueDistributionAnswer.tag

A copy of the answer to “Should quarterly F&A Revenue Distribution be allocated based on actual sibling activity rather than F&A credit split panel distribution?” will be placed on the Key Personnel tab below the Combined Split Credit and above the close button

UAR-1755: Proposal Key Personnel: add specific question and its answer

---

src/main/webapp/scripts/ua_kuali_application.js

1) Change jQuery selector to only find anchor tags from the lookup results where the href contains 'displayDocSearchView' in the url. These are the links associated with the the Document Id from the Document Search and the Actions links.
2) Apply logic to make sure that the loading screen only shows if the anchor tag target opens on the same tab to prevent the lookup links from the Proposal Routing Dashboard to be affected.

UAR-2576 Apply the loading page to only apply to Actions and Document Id links

---

src/main/java/org/kuali/kra/irb/ProtocolAction.java
src/main/resources/edu/arizona/kc/db/changelog/changesets/db.changelog-UAR-2818.xml
src/main/resources/edu/arizona/kc/db/changelog/db.changelog-master.xml

1) Modify ProtocolAction.java to also check whether the type code of an attachment is valid before applying the watermark. 
2) Add liquibase changeset to create the new watermark parameter.

UAR-2818 Apply IRB PDF watermarks to only Informed Consent/PHI Form attachment types

---

src/main/java/org/kuali/kra/common/committee/web/struts/action/CommitteeActionBase.java

Override the saveOnClose() method to call private helper method closeCommitteeDocument() to save the committee document using the kraDocumentService rather than the documentService used in the close method in rice KualiDocumentActionBase.

UAR-1851 Saved (not submitted) Committee document edits will still create rows in the database which cause issues

---

src/main/java/org/kuali/kra/protocol/personnel/PersonnelHelperBase.java

Fix initializes the units and attachments array in PersonnelHelperBase to be displayed in the corresponding .tag files from the Personnel tab.

UAR-2898: Personnel tab only partially loading personnel causes HTTP Status 500 Error

---

src/main/java/org/kuali/kra/award/web/struts/action/AwardAction.java
src/main/java/org/kuali/kra/award/web/struts/action/AwardContactsAction.java
src/main/java/org/kuali/kra/infrastructure/KeyConstants.java
src/main/resources/ApplicationResources.properties

1) Move setLeadUnitOnAwardFromPILeadUnit() method from subclass AwardContactsAction.java to superclass AwardAction.java.  Remove unused awardForm variable. Call this method in  AwardAction#save() so that the lead unit is updated when saving from all the tabs on the Award document.
2) Add validation message when a user can't save from the Contacts tab.

UAR-2802 Unable to change lead unit when versioning an award
