ua-eas/ksd-kc5.2.1-ua

src/main/java/org/kuali/kra/infrastructure/KeyConstants.java
src/main/java/org/kuali/kra/s2s/service/impl/S2SUtilServiceImpl.java

_Important_: There will be a corresponding kc_project pull request for this jira
* Added key values to KeyConstants for parms that will be used as SPS contact info
* Modified logic in java to pull parms for contact info instead of Person object

UAR-898 - Generic 'address', 'phone', 'email', and 'fax' solution needed for GG form mapping

---

src/main/webapp/css/uar_kuali_application.css

Added CSS to hide the S2S tab when it is disabled.

UAR-913 UI issues with S2S tab

---

src/main/java/org/kuali/kra/budget/core/Budget.java

Added code to sort by job code for displaying academic then summer on the budget tab in the project personnel panel.

UAR-979 budget personnel sort order

---

src/main/java/org/kuali/kra/proposaldevelopment/document/authorization/ProposalDevelopmentDocumentAuthorizer.java

There will be a merge conflict on this, because the base file was not in the master branch.

UAR-1045 Blanket Approve button not showing

---

src/main/resources/edu/arizona/kc/db/changelog/changesets/db.changelog-UAR-1002.xml
src/main/resources/edu/arizona/kc/db/changelog/db.changelog-master.xml
src/main/resources/org/kuali/kra/datadictionary/NegotiationAgreementType.xml

UAR-993: Negotiation Log migration is dependent of the fixes in this ticket

UAR-1002, UAR-993 Negotiation Agreement Type - Description increase field length to 50.

---

src/main/java/edu/arizona/kra/institutionalproposal/negotiationlog/service/NegotiationLogMigrationServiceImpl.java

This fix depends on UAR-993 and on UAR-1049

UAR-1078, UAR-993: Adding code in NegotiationMigrationService for migrating NegotiationLog.account into Negotiation.accountId

---

src/main/java/edu/arizona/kra/institutionalproposal/negotiationlog/service/NegotiationLogMigrationServiceImpl.java

Added additional code to push the Negotiation Workflow Document through the workflow engine to be final at the first save. (same as the newly negotiations in 5.2.1).

UAR-993, UAR-1081: Set the workflow document to FINALIZED after SAVE

---

src/main/resources/edu/arizona/kc/db/changelog/changesets/db.changelog-UAR-481.xml
src/main/resources/edu/arizona/kc/db/changelog/db.changelog-master.xml
src/main/webapp/WEB-INF/tags/customdata/customData.tag

This fix adds a new custom data tag named Boolean for Y/N displayed with a radio button.

UAR-481: Implementing IU fix for adding a Y/N radio button Boolean custom data attribute

---

src/main/java/org/kuali/kra/budget/versions/BudgetVersionOverview.java
src/main/java/org/kuali/kra/budget/web/struts/action/BudgetParametersAction.java
src/main/java/org/kuali/kra/proposaldevelopment/web/struts/action/ProposalDevelopmentAction.java
src/main/java/org/kuali/kra/proposaldevelopment/web/struts/action/ProposalDevelopmentActionsAction.java
src/main/resources/org/kuali/kra/budget/repository-budget.xml
src/main/resources/org/kuali/kra/datadictionary/Budget.xml

There were several issues fixed under this ticket.

UAR-959 Budget Data Override not working, causes stack trace error

---

src/main/resources/org/kuali/kra/datadictionary/Sponsor.xml

in the UI only. Database already has field size set to 30.

UAR-1357 change size of Sponsor Acronym field to 30.

---

src/main/resources/edu/arizona/kc/db/changelog/changesets/db.changelog-UAR-1444.xml
src/main/resources/edu/arizona/kc/db/changelog/db.changelog-master.xml
src/main/resources/org/kuali/kra/datadictionary/AwardApprovedSubawards.xml
src/main/resources/org/kuali/kra/datadictionary/ProposalSite.xml
src/main/resources/org/kuali/kra/datadictionary/SubAward.xml

merge conflict due to master changelog.

UAR-1444 Adjust column width for Organization Name fields in Subaward, Award, Proposal Development, and Proposal Budget

---

src/main/config/xsd/printing/irb.xsd
src/main/java/edu/arizona/kra/irb/actions/print/CustomProtocolXmlStream.java

UAR-263 XML: missing questionnaire details

---

pom.xml

Changed the pom.xml to reflect the new rice version from 2.3.6 to 2.3.7

UAR-1442 Upgrading rice version to 2.3.7

---

src/main/webapp/WEB-INF/tags/medusa/medusaSubAwardSummary.tag
src/main/webapp/WEB-INF/tags/medusa/medusaTreeNode.tag

Implementing IU patch for KRAFDBCK-10733 - System Should Display Subaward ID Not Subaward Version on Medusa Hierarchy and Medusa Subpanel

UAR-1480: Subaward ID sequencing issues in UI and Database

---

src/main/java/org/kuali/kra/award/AwardDocumentRule.java
src/main/java/org/kuali/kra/negotiations/rules/NegotiationActivityAttachmentRuleImpl.java
src/main/java/org/kuali/kra/proposaldevelopment/rules/ProposalDevelopmentPersonnelAttachmentRule.java
src/main/java/org/kuali/kra/protocol/noteattachment/AddProtocolAttachmentProtocolRuleImplBase.java
src/main/java/org/kuali/kra/subaward/subawardrule/SubAwardDocumentRule.java
src/main/java/org/kuali/kra/web/struts/form/KraTransactionalDocumentFormBase.java
src/main/webapp/WEB-INF/tags/award/awardAttachments.tag
src/main/webapp/WEB-INF/tags/irb/protocolAttachmentProtocol.tag
src/main/webapp/WEB-INF/tags/negotiation/negotiationActivity.tag
src/main/webapp/WEB-INF/tags/proposaldevelopment/proposalDevelopmentAttachments.tag
src/main/webapp/WEB-INF/tags/proposaldevelopment/proposalDevelopmentInstitutionalAttachments.tag
src/main/webapp/WEB-INF/tags/proposaldevelopment/proposalDevelopmentPersonnelAttachments.tag
src/main/webapp/WEB-INF/tags/subaward/subAwardAttachment.tag
src/main/webapp/WEB-INF/tags/subaward/subAwardHistoryOfChanges.tag
src/main/webapp/scripts/fileUpload.js

Added a maxAttachmentSize variable to KraTransactionalDocumentFormBase.java so the pages have access to max attachment size. Added new file fileUpload.js which checks the file being uploaded and if it's too large, gives a warning and prevents the user from attaching the file. For the rest of the files, I added the imports to call the newly added JavaScript validation.

UAR-1313_2

---

src/main/java/org/kuali/kra/award/web/struts/action/AwardAction.java
src/main/java/org/kuali/kra/award/web/struts/action/AwardHomeAction.java
src/main/java/org/kuali/kra/medusa/service/MedusaServiceImpl.java
src/main/java/org/kuali/kra/service/VersionHistoryService.java
src/main/java/org/kuali/kra/service/impl/VersionHistoryServiceImpl.java
src/main/java/org/kuali/kra/subaward/SubAwardForm.java
src/main/java/org/kuali/kra/subaward/bo/SubAward.java
src/main/java/org/kuali/kra/subaward/bo/SubAwardFundingSource.java
src/main/java/org/kuali/kra/subaward/service/SubAwardService.java
src/main/java/org/kuali/kra/subaward/service/impl/SubAwardServiceImpl.java
src/main/webapp/WEB-INF/tags/subaward/subAwardFundingSource.tag

Tech Notes: Jira tickets UAR-1191, UAR-1468 and UAR-1497 are all due to how the Award/Subaward are versioned and linked to Subaward Funding Sources. 
Subaward Funding Sources are objects that link both to a certain version of the Award (by linking with AwardId) and Subaward (linking with Subaward code). When an Award is edited, a new version of it gets created and such, a new AwardId. When the user opens the new Award, the link from the initial Subaward Funding Source has 'dissapeared'... because it doesn't exist for this version since it points to the 'old' AwardId.
When a Subaward is edited, the same thing happens, only that in this case, with the new version of the SubAward, also a new SubawardFundingSource object is also created. (note that SubawardFundingSource don't have …

UAR 1497 - Subaward link not removing from Award if deleted

---

src/main/resources/edu/arizona/kc/db/changelog/changesets/db.changelog-UAR-1497.xml

and spacing in the changelog file

UAR-1497: Fixing syntax error in rollback statement

---

src/main/java/org/kuali/kra/subaward/dao/impl/SubAwardFundingSourceDaoOjb.java

The medusa views are created in a non-transactional context, so the SubAwardFundingSourceDAO couldn't get a hold of a PersistenceBroker due to using getPersistenceBroker(false). I've changed that so the DAO can create a PB instance if none is existing and taking care that it's also released at the end of the work.

UAR-1497: Fixing issues with MEDUSA views

---

src/main/java/org/kuali/kra/award/home/Award.java
src/main/resources/org/kuali/kra/datadictionary/Award.xml

Fixing issues with amountObligatedToDate in Award.xml being declared as a date instead of amount.
Removing redundant entries.

UAR-1628: Fixing award editing issue

---

src/main/resources/META-INF/kc-config-defaults.xml

<param name="email.reminder.lifecycle.enabled">true</param>

Adding an additional parameter to enable the emailLifecycle in KEW

---

src/main/webapp/WEB-INF/dwr-ua.xml
src/main/webapp/WEB-INF/tags/subaward/subAwardFundingSource.tag
src/main/webapp/scripts/ua_kuali_application.js

Fixing inconsistencies in .tag and .js and lookup for AwardNumber resulting in award number being wrongly populated with 000000-0000

UAR-1919: Fixing issues with awardNumber at lookup and search

---

src/main/java/org/kuali/kra/award/home/Award.java
src/main/java/org/kuali/kra/dao/VersionHistoryLookupDao.java
src/main/java/org/kuali/kra/dao/ojb/AwardLookupDaoOjb.java
src/main/java/org/kuali/kra/dao/ojb/VersionHistoryLookupDaoOjb.java
src/main/java/org/kuali/kra/subaward/bo/SubAward.java
src/main/java/org/kuali/kra/subaward/dao/SubAwardFundingSourceDao.java
src/main/java/org/kuali/kra/subaward/dao/SubAwardLookupDao.java
src/main/java/org/kuali/kra/subaward/dao/impl/SubAwardFundingSourceDaoOjb.java
src/main/java/org/kuali/kra/subaward/dao/impl/SubAwardLookupDaoOjb.java
src/main/java/org/kuali/kra/subaward/lookup/SubAwardLookupableHelperServiceImpl.java
src/main/java/org/kuali/kra/subaward/service/SubAwardService.java
src/main/java/org/kuali/kra/subaward/service/impl/SubAwardServiceImpl.java
src/main/resources/org/kuali/kra/datadictionary/SubAward.xml
src/main/resources/org/kuali/kra/subaward/SubAwardSpringBeans.xml
src/main/resources/org/kuali/kra/subaward/repository-subAward.xml
src/main/webapp/WEB-INF/tags/subaward/subAwardHistoryOfChanges.tag

UAR-1685: SubAward Lookup refactoring
UAR-1685: Adding special requirements for requisitioner name and organization name
UAR-1685: Completely refactored subaward lookup

UAR-1685: Fixing and refactoring SubAward Lookup to match limits and remove user specific filtering

---

src/main/java/edu/arizona/kra/negotiations/NegotiationConstants.java
src/main/java/edu/arizona/kra/negotiations/dao/ojb/NegotiationLookupDaoOjb.java
src/main/java/org/kuali/kra/negotiations/lookup/NegotiationLookupableHelperServiceImpl.java

Adding additional criteria for the principal investigator name

UAR-2140: Fixing issue with the Principal investigator name search

---

src/main/java/edu/arizona/kra/proposaldevelopment/service/impl/PropDevRoutingStateLookupableHelperServiceImpl.java

This is a temporary revert to the sorting order previous to release 27 .

UAR-2395: Temporary sorting order for proposal routing dashboard

---

src/main/java/edu/arizona/kra/irb/CustomProtocolForm.java
src/main/java/edu/arizona/kra/irb/actions/CustomActionHelper.java
src/main/java/org/kuali/kra/irb/ProtocolAction.java
src/main/java/org/kuali/kra/irb/ProtocolForm.java
src/main/java/org/kuali/kra/irb/actions/ActionHelper.java
src/main/java/org/kuali/kra/irb/actions/IrbProtocolActionRequestServiceImpl.java
src/main/java/org/kuali/kra/irb/actions/ProtocolProtocolActionsAction.java
src/main/java/org/kuali/kra/irb/actions/modifysubmission/ProtocolModifySubmissionBean.java
src/main/java/org/kuali/kra/irb/personnel/ProtocolPersonnelAction.java
src/main/java/org/kuali/kra/irb/protocol/ProtocolProtocolAction.java
src/main/java/org/kuali/kra/protocol/ProtocolActionBase.java
src/main/java/org/kuali/kra/protocol/ProtocolBase.java
src/main/java/org/kuali/kra/protocol/ProtocolFormBase.java
src/main/java/org/kuali/kra/protocol/actions/ActionHelperBase.java

This addresses the following performance fixes from foundation:
RESKC-1069:Protocol Performance Issue https://github.com/kuali/kc/commit/aaf1342068c2f393d21bc0db34f456ea2a1b30d5
And the following fixes to mend the issues after RESKC-1069....
RESKC-1123:Prevent NPE from occuring when permissions helper has not …
…yet been inititialized
https://github.com/kuali/kc/commit/ca1c4f906e5cb5e781e3a4240c90be4e497adaa4
RESKC-1089:IRB - STE when saving data in the Personnel tab
https://github.com/kuali/kc/commit/3b2bf814dc409e5385f534910861e303c6e51385

UAR-1957: IRB Tab Navigation Performance Fixes

---

src/main/webapp/WEB-INF/jsp/negotiation/NegotiationMedusa.jsp
src/main/webapp/WEB-INF/jsp/negotiation/NegotiationNegotiation.jsp
src/main/webapp/WEB-INF/tags/negotiation/negotiationActivity.tag

Fixed jQuery var jq has not been properly initalized at page load. Also fied the "Page is loading" pop-up to be removed when file is downloaded completely

UAR-2957: Radio button to toggle between "Pending" and "All" negotiation activities is not working

---

src/main/java/org/kuali/kra/award/contacts/AwardProjectPersonnelBean.java
src/main/java/org/kuali/kra/award/web/struts/action/AwardHomeAction.java

Add the lead unit selected back into the award on the save action.

UAR-2802 Unable to change lead unit when versioning an award
